baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'LinkedOut - Thomas Dion'

[params]
  authorName = "Thomas Dion"
  headline = "Account Manager | Product Owner | Python Automation Enthusiast | $300K+ ARR Generator"
  profileViewers = "350+ (mostly prospects I cold called)"
  postImpressions = "53,000 contacts generated"

  recentItems = [
    "Sales Automation Nerds",
    "#PythonForSales",
    "#ColdCallingChampion",
    "#ProductManagement"
  ]

  [[params.newsItems]]
    title = "Account Manager automates sales with Python, saves 200 hours"
    time = "2h ago"
    readers = "10,847"

  [[params.newsItems]]
    title = "Cold calling still works: 2.4% conversion rate beats email"
    time = "4h ago"
    readers = "8,294"

  [[params.newsItems]]
    title = "Product Owners who code ship 3x faster features"
    time = "6h ago"
    readers = "5,621"

  [[params.newsItems]]
    title = "AI-powered SEO content: Hype or game-changer?"
    time = "8h ago"
    readers = "12,394"

  [[params.newsItems]]
    title = "Sales + Tech skills = Competitive advantage in 2025"
    time = "1d ago"
    readers = "7,103"
