baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'LinkedOut - Professional Portfolio Parody'

[params]
  authorName = "Your Name Here"
  headline = "Professional Procrastinator | Coffee-to-Code Converter | Bug Creator & Destroyer"
  profileViewers = "3 (all you)"
  postImpressions = "Mostly depression"

  recentItems = [
    "Stack Overflow Copy-Pasters",
    "#debugging-at-3am",
    "#works-on-my-machine"
  ]

  [[params.newsItems]]
    title = "\"Senior\" devs admit they still Google basic syntax"
    time = "2h ago"
    readers = "10,847"

  [[params.newsItems]]
    title = "Study finds 99% of LinkedIn posts are humble brags"
    time = "4h ago"
    readers = "8,294"

  [[params.newsItems]]
    title = "New framework released, nobody asked for it"
    time = "6h ago"
    readers = "5,621"

  [[params.newsItems]]
    title = "Developer solves problem by turning it off and on"
    time = "8h ago"
    readers = "12,394"

  [[params.newsItems]]
    title = "\"It's not a bug, it's a feature\" now official policy"
    time = "1d ago"
    readers = "7,103"
